ALTER TABLE NAVIGATOR.GPS_COMP_SG
 DROP PRIMARY KEY CASCADE;

DROP TABLE NAVIGATOR.GPS_COMP_SG CASCADE CONSTRAINTS;

CREATE TABLE NAVIGATOR.GPS_COMP_SG
(
  SCOD             NUMBER,
  PL_NMB           NUMBER,
  PL_DAT           DATE,
  BEG_DAT          DATE,
  END_DAT          DATE,
  GAR_NMB          NUMBER(6),
  GOS_NMB          VARCHAR2(32 BYTE),
  GOS_NMBD         VARCHAR2(5 BYTE),
  MARK_NAME        VARCHAR2(300 BYTE),
  CEH              NUMBER(5),
  NGDU             NUMBER(5),
  DEVICEID         NUMBER,
  GPS_KM           NUMBER(8,2),
  PL_KM            NUMBER(8,2),
  OTKL_KM          NUMBER(8,2),
  OTKL_PRC         NUMBER(5),
  MAX_V            NUMBER(8,2),
  AVG_V            NUMBER(8,2),
  FACT             NUMBER(8,2),
  NORM             NUMBER(8,2),
  OTKL_PROBEG_KM   NUMBER(8,2),
  OTKL_PROBEG_PRC  NUMBER(5),
  BEG_TOPL_GPS     NUMBER(8,2),
  END_TOPL_GPS     NUMBER(8,2),
  PDRZ_NAME        VARCHAR2(300 BYTE),
  BEG_TOPL         NUMBER(8,2),
  IN_TOPL          NUMBER(8,2),
  END_TOPL         NUMBER(8,2),
  OUT_TOPL         NUMBER(8,2),
  GPS_KM_WO_JUMPS  NUMBER(8,2)
)
TABLESPACE NAVITBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NAVIGATOR.GPS_COMP_SG_PK ON NAVIGATOR.GPS_COMP_SG
(SCOD)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_PL_NMB_IDX ON NAVIGATOR.GPS_COMP_SG
(PL_NMB)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_PL_DAT_IDX ON NAVIGATOR.GPS_COMP_SG
(PL_DAT)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_BEG_DAT_IDX ON NAVIGATOR.GPS_COMP_SG
(BEG_DAT)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_END_DAT_IDX ON NAVIGATOR.GPS_COMP_SG
(END_DAT)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_OTKL_PROB_PRC_IDX ON NAVIGATOR.GPS_COMP_SG
(OTKL_PROBEG_PRC)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_GOS_NMB_IDX ON NAVIGATOR.GPS_COMP_SG
(GOS_NMB)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_NGDU_IDX ON NAVIGATOR.GPS_COMP_SG
(NGDU)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_DEVICEID_IDX ON NAVIGATOR.GPS_COMP_SG
(DEVICEID)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_OTKL_PRC_IDX ON NAVIGATOR.GPS_COMP_SG
(OTKL_PRC)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX NAVIGATOR.GPS_COMP_SG_GAR_NMB_IDX ON NAVIGATOR.GPS_COMP_SG
(GAR_NMB)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE NAVIGATOR.GPS_COMP_SG ADD (
  CONSTRAINT GPS_COMP_SG_PK
  PRIMARY KEY
  (SCOD)
  USING INDEX NAVIGATOR.GPS_COMP_SG_PK
  ENABLE VALIDATE);
