DROP TABLE NAVIGATOR.GPS_PARK CASCADE CONSTRAINTS;

CREATE TABLE NAVIGATOR.GPS_PARK
(
  ATC_NMB     NUMBER,
  GAR_SCOD    NUMBER,
  GAR_NMB     NUMBER(6),
  GOS_NMB     VARCHAR2(96 BYTE),
  GOS_NMBD    VARCHAR2(15 BYTE),
  PDRZ_COD    NUMBER(5),
  PDRZ_NAME   VARCHAR2(900 BYTE),
  MARK_NAME   VARCHAR2(900 BYTE),
  UST_DAT     DATE,
  DEMONT_DAT  DATE,
  OBOR_NAME   VARCHAR2(900 BYTE),
  GPS_BLOCK   VARCHAR2(90 BYTE)
)
TABLESPACE NAVITBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
