ALTER TABLE NAVIGATOR.GPS_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE NAVIGATOR.GPS_LOG CASCADE CONSTRAINTS;

CREATE TABLE NAVIGATOR.GPS_LOG
(
  F1  VARCHAR2(100 BYTE)
)
TABLESPACE NAVITBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NAVIGATOR.PK1_LOG ON NAVIGATOR.GPS_LOG
(F1)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE NAVIGATOR.GPS_LOG ADD (
  CONSTRAINT PK1_LOG
  PRIMARY KEY
  (F1)
  USING INDEX NAVIGATOR.PK1_LOG
  ENABLE VALIDATE);
