ALTER TABLE NAVIGATOR.SENSORS
 DROP PRIMARY KEY CASCADE;

DROP TABLE NAVIGATOR.SENSORS CASCADE CONSTRAINTS;

CREATE TABLE NAVIGATOR.SENSORS
(
  ID           NUMBER,
  SENSOR_NAME  VARCHAR2(10 BYTE)
)
TABLESPACE NAVITBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NAVIGATOR.SENSOR_PK ON NAVIGATOR.SENSORS
(ID)
LOGGING
TABLESPACE NAVITBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE NAVIGATOR.SENSORS ADD (
  CONSTRAINT SENSOR_PK
  PRIMARY KEY
  (ID)
  USING INDEX NAVIGATOR.SENSOR_PK
  ENABLE VALIDATE);
